// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VideoService is the Go backend bound to the React frontend. It wraps
 * ffmpeg/ffprobe to probe and produce videos locally.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * PickFile opens a native file picker and returns the chosen path.
 */
export function PickFile(): $CancellablePromise<string> {
    return $Call.ByID(908654365);
}

/**
 * PickFolder opens a native folder picker for the output directory.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(2266940807);
}

/**
 * Probe returns metadata for the file at path.
 */
export function Probe(path: string): $CancellablePromise<$models.VideoInfo> {
    return $Call.ByID(2706873020, path);
}

/**
 * Produce writes the output in the chosen container at (approximately) the
 * target size. If targetBytes is at/above the original size, it only changes
 * the container losslessly (-c copy, no quality loss, same size). Otherwise it
 * two-pass encodes to hit the target size.
 */
export function Produce(path: string, targetBytes: number, targetHeight: number, container: string, outDir: string, outName: string): $CancellablePromise<$models.ConvertResult> {
    return $Call.ByID(3239688558, path, targetBytes, targetHeight, container, outDir, outName);
}
