// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConvertResult is returned after a produce operation.
 */
export interface ConvertResult {
    "outputPath": string;
    "outputName": string;
    "inputSizeBytes": number;
    "outputSizeBytes": number;
}

/**
 * VideoInfo is the metadata shown for the selected file.
 */
export interface VideoInfo {
    "path": string;
    "name": string;
    "sizeBytes": number;
    "width": number;
    "height": number;
    "duration": number;
    "codec": string;
    "container": string;
}
